version: '3.9'
services:
  frontend:
    container_name: policy-insurance-dashboard
    build: .
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    image: node:20-alpine
    working_dir: /app
    command: ["npm", "run", "start"]
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
